version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: tasks-database
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
  app:
    container_name: node
    image: node:18
    working_dir: /usr/app
    command: bash -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - postgres

volumes:
    pgdata:
        driver: local