version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: tasks-database
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
volumes:
    pgdata:
        driver: local